-- Labor-market intelligence engine, phase 2:
--   Profession          — admin-managed profession taxonomy (reference data;
--                         Worker.primaryTrade stays free text, resolved by
--                         slug / name / alias matching)
--   Skill.version       — skill definitions are versioned; metrics record the
--                         version they were computed against
--   Skill.nameEn        — secondary-language skill name (i18n readiness)
--   InsightArticle      — autoGenerated + generatedFrom (drafts written by the
--                         insights generator carry full provenance; an admin
--                         reviews before publishing)
--
-- Group is intentionally a plain text column (not an enum): administrators add
-- profession groups (technical, healthcare, transport, engineering, …) without
-- a migration. All statements are idempotent (IF NOT EXISTS / DO-blocks).

CREATE TABLE IF NOT EXISTS "Profession" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "nameEn" TEXT,
    "group" TEXT NOT NULL,
    "description" TEXT,
    "aliases" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Profession_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "Profession_slug_key" ON "Profession"("slug");
CREATE INDEX IF NOT EXISTS "Profession_group_isActive_idx" ON "Profession"("group", "isActive");
CREATE INDEX IF NOT EXISTS "Profession_isActive_sortOrder_idx" ON "Profession"("isActive", "sortOrder");

ALTER TABLE "Skill" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;
ALTER TABLE "Skill" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "InsightArticle" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "InsightArticle" ADD COLUMN IF NOT EXISTS "generatedFrom" JSONB;
CREATE INDEX IF NOT EXISTS "InsightArticle_autoGenerated_idx" ON "InsightArticle"("autoGenerated");