import { InsightsGeneratorService } from '../insights-generator.service';
import { InsightsConfigService } from '../insights-config.service';
import { DEFAULT_GENERATOR_CONFIG, DEFAULT_THRESHOLDS } from '../insights-settings';

const DAY = 24 * 60 * 60 * 1000;

function makeConfig(overrides: { thresholds?: Partial<typeof DEFAULT_THRESHOLDS>; generator?: Partial<typeof DEFAULT_GENERATOR_CONFIG> } = {}): InsightsConfigService {
  return {
    getThresholds: jest.fn().mockResolvedValue({ ...DEFAULT_THRESHOLDS, ...overrides.thresholds }),
    getGeneratorConfig: jest.fn().mockResolvedValue({ ...DEFAULT_GENERATOR_CONFIG, ...overrides.generator }),
    updateThresholds: jest.fn(),
    updateGeneratorConfig: jest.fn(),
    invalidateCache: jest.fn(),
  } as any;
}

function trendPoint(overrides: Partial<Record<string, any>> = {}) {
  return {
    date: '2026-07-01',
    label: '2026-07',
    salaryMedian: { available: true, value: 48000, sampleSize: 40 },
    offers: 40,
    employers: 10,
    changePct: 5,
    ...overrides,
  };
}

function makePrisma(overrides: Partial<Record<string, any>> = {}) {
  return {
    marketSnapshot: {
      findMany: jest.fn().mockResolvedValue([{ profession: 'Electrician', regionId: null }]),
      findFirst: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
      count: jest.fn(),
      findUnique: jest.fn(),
      deleteMany: jest.fn(),
    },
    insightArticle: {
      findFirst: jest.fn().mockResolvedValue(null),
      create: jest.fn().mockImplementation(({ data }) => Promise.resolve({ id: 'new', ...data })),
      findMany: jest.fn(),
      count: jest.fn(),
    },
    region: { findUnique: jest.fn().mockResolvedValue({ name: 'Utrecht' }) },
  };
}

function makeService(prisma: any, config: InsightsConfigService, trends: any, aggregation: any = {}) {
  const snapshots = { getTrends: jest.fn().mockResolvedValue(trends) };
  const aggregationService = {
    getAggregate: jest.fn().mockResolvedValue({ competitiveness: { benefitCompetitiveness: { available: false } } }),
    getSkillDemandStats: jest.fn().mockResolvedValue(aggregation.skillDemand ?? []),
    ...aggregation,
  };
  const service = new InsightsGeneratorService(
    prisma as any,
    makeConfig(),
    aggregationService as any,
    snapshots as any,
  );
  return { service, prisma, snapshots, aggregationService };
}

describe('InsightsGeneratorService — draft generation', () => {
  it('is a no-op when the generator is disabled', async () => {
    const prisma = makePrisma();
    const { service } = makeService(prisma, undefined as any, { points: [] }, undefined);
    // Rebuild with a disabled config: easiest via a dedicated instance.
    const config = {
      getThresholds: jest.fn().mockResolvedValue({ ...DEFAULT_THRESHOLDS }),
      getGeneratorConfig: jest.fn().mockResolvedValue({ ...DEFAULT_GENERATOR_CONFIG, enabled: false }),
    } as any;
    const disabled = new InsightsGeneratorService(prisma as any, config, { getSkillDemandStats: jest.fn() } as any, { getTrends: jest.fn() } as any);

    const result = await disabled.generateDrafts();

    expect(result).toEqual({ created: [], skipped: 0, enabled: false });
    expect(prisma.insightArticle.create).not.toHaveBeenCalled();
  });

  it('writes a DRAFT article (never published) with autoGenerated + ruleKey provenance', async () => {
    const prisma = makePrisma();
    // The generator takes the last two available points of the monthly series.
    const clean = {
      points: [
        trendPoint({ label: '2026-06', salaryMedian: { available: true, value: 45000, sampleSize: 40 }, changePct: null }),
        trendPoint({ label: '2026-07', salaryMedian: { available: true, value: 48000, sampleSize: 45 }, changePct: 6.7 }),
      ],
    };
    const { service } = makeService(prisma, undefined as any, clean, undefined);

    const result = await service.generateDrafts();

    expect(result.enabled).toBe(true);
    expect(result.created).toHaveLength(1);
    expect(result.created[0].rule).toBe('SALARY_CHANGE');

    const data = prisma.insightArticle.create.mock.calls[0][0].data;
    expect(data.status).toBe('DRAFT');
    expect(data.autoGenerated).toBe(true);
    expect(data.generatedFrom.rule).toBe('SALARY_CHANGE');
    expect(data.generatedFrom.ruleKey).toBe('salary:Electrician:country:2026-07');
    expect(data.dataClass).toBe('OFFERMARKT');
    expect(data.content).toContain('not been reviewed by an editor yet');
    // Combined sample must clear 2×SALARY_RANGE.
    expect(data.generatedFrom.curPoint.sample + data.generatedFrom.prevPoint.sample).toBeGreaterThanOrEqual(60);
  });

  it('does not regenerate a draft whose ruleKey already exists (idempotent)', async () => {
    const prisma = makePrisma();
    prisma.insightArticle.findFirst.mockResolvedValue({ id: 'existing' });
    const clean = {
      points: [
        trendPoint({ label: '2026-06', salaryMedian: { available: true, value: 45000, sampleSize: 40 }, changePct: null }),
        trendPoint({ label: '2026-07', salaryMedian: { available: true, value: 48000, sampleSize: 45 }, changePct: 6.7 }),
      ],
    };
    const { service } = makeService(prisma, undefined as any, clean, undefined);

    const result = await service.generateDrafts();

    expect(result.created).toHaveLength(0);
    expect(result.skipped).toBe(1);
    expect(prisma.insightArticle.create).not.toHaveBeenCalled();
  });

  it('stays silent when the change is below the configured trigger level', async () => {
    const prisma = makePrisma();
    const clean = {
      points: [
        trendPoint({ label: '2026-06', salaryMedian: { available: true, value: 47800, sampleSize: 40 }, changePct: null }),
        trendPoint({ label: '2026-07', salaryMedian: { available: true, value: 48000, sampleSize: 45 }, changePct: 0.4 }),
      ],
    };
    const { service } = makeService(prisma, undefined as any, clean, undefined);

    const result = await service.generateDrafts();

    // Salary rule silent; no other rule has data.
    expect(result.created).toHaveLength(0);
    expect(prisma.insightArticle.create).not.toHaveBeenCalled();
  });
});

describe('InsightsGeneratorService — demand growth rule', () => {
  it('drafts a DEMAND article when a skill clears the growth minimum', async () => {
    const prisma = makePrisma();
    const aggregation = {
      getAggregate: jest.fn().mockResolvedValue({ competitiveness: { benefitCompetitiveness: { available: false } } }),
      getSkillDemandStats: jest.fn().mockResolvedValue([
        { skill: 'ev-installation', offers: 25, prevOffers: 15, growthPct: 66.7 },
      ]),
    };
    const snapshots = { getTrends: jest.fn().mockResolvedValue({ points: [] }) };
    const service = new InsightsGeneratorService(
      prisma as any,
      {
        getThresholds: jest.fn().mockResolvedValue({ ...DEFAULT_THRESHOLDS }),
        getGeneratorConfig: jest.fn().mockResolvedValue({ ...DEFAULT_GENERATOR_CONFIG }),
      } as any,
      aggregation as any,
      snapshots as any,
    );

    const result = await service.generateDrafts();

    expect(result.created).toHaveLength(1);
    expect(result.created[0].rule).toBe('DEMAND_GROWTH');
    const data = prisma.insightArticle.create.mock.calls[0][0].data;
    expect(data.category).toBe('DEMAND');
    expect(data.status).toBe('DRAFT');
    expect(data.skills).toEqual(['ev-installation']);
  });

  it('ignores growth from small samples (growthPct null)', async () => {
    const prisma = makePrisma();
    const aggregation = {
      getAggregate: jest.fn().mockResolvedValue({ competitiveness: { benefitCompetitiveness: { available: false } } }),
      getSkillDemandStats: jest.fn().mockResolvedValue([
        { skill: 'tiny-skill', offers: 3, prevOffers: 2, growthPct: null },
      ]),
    };
    const service = new InsightsGeneratorService(
      prisma as any,
      {
        getThresholds: jest.fn().mockResolvedValue({ ...DEFAULT_THRESHOLDS }),
        getGeneratorConfig: jest.fn().mockResolvedValue({ ...DEFAULT_GENERATOR_CONFIG }),
      } as any,
      aggregation as any,
      { getTrends: jest.fn().mockResolvedValue({ points: [] }) } as any,
    );

    const result = await service.generateDrafts();
    expect(result.created).toHaveLength(0);
  });
});