import { Injectable, Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../../prisma/prisma.service';
import { InsightsConfigService } from './insights-config.service';
import { MarketAggregationService } from './market-aggregation.service';
import { InsightsSnapshotService } from './insights-snapshot.service';
import { METHOD_VERSION, round1 } from './insights-settings';

/**
 * InsightsGeneratorService — automatic detection of interesting market
 * changes (P6). Every generated article is written with status DRAFT and
 * `autoGenerated: true`: an administrator reviews and publishes it, always.
 * Nothing here auto-publishes — the generator only fills the review queue.
 *
 * Rules (each fires only when the sample-size thresholds clear, and each
 * carries full provenance in `generatedFrom`):
 *   SALARY_CHANGE   — monthly median salary delta per (profession, region)
 *   DEMAND_GROWTH   — per-skill offer growth between consecutive windows
 *   BENEFIT_IMPACT  — acceptance-rate gap between strong vs weak benefit packages
 */
type RuleId = 'SALARY_CHANGE' | 'DEMAND_GROWTH' | 'BENEFIT_IMPACT';

export interface GenerationResult {
  created: Array<{ slug: string; rule: RuleId; profession: string | null; regionId: string | null }>;
  skipped: number;
  enabled: boolean;
}

const MAX_DRAFTS_PER_RUN = 10;

@Injectable()
export class InsightsGeneratorService {
  private readonly logger = new Logger(InsightsGeneratorService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: InsightsConfigService,
    private readonly aggregation: MarketAggregationService,
    private readonly snapshots: InsightsSnapshotService,
  ) {}

  /** Runs nightly after the snapshot job (2:30) — drafts land before morning. */
  @Cron('0 45 2 * *')
  async nightlyGenerate() {
    await this.generateDrafts();
  }

  async generateDrafts(): Promise<GenerationResult> {
    const cfg = await this.config.getGeneratorConfig();
    if (!cfg.enabled) {
      return { created: [], skipped: 0, enabled: false };
    }
    const created: GenerationResult['created'] = [];
    let skipped = 0;

    const budget = {
      salary: async () => this.salaryChangeDrafts(cfg.salaryChangePct),
      demand: async () => this.demandGrowthDrafts(cfg.demandGrowthPct),
      benefit: async () => this.benefitImpactDrafts(cfg.benefitMinSample, cfg.benefitMinGapPct),
    };

    for (const run of [budget.salary, budget.demand, budget.benefit]) {
      if (created.length >= MAX_DRAFTS_PER_RUN) break;
      const drafts = await run();
      for (const draft of drafts) {
        if (created.length >= MAX_DRAFTS_PER_RUN) break;
        const exists = await this.findByRuleKey(draft.ruleKey);
        if (exists) {
          skipped += 1;
          continue;
        }
        await this.prisma.insightArticle.create({
          data: {
            slug: draft.slug,
            title: draft.title,
            summary: draft.summary,
            category: draft.category,
            content: draft.content,
            profession: draft.profession,
            regionId: draft.regionId,
            skills: draft.skills,
            charts: draft.charts as Prisma.InputJsonValue[],
            statistics: draft.statistics as Prisma.InputJsonValue[],
            keyStats: draft.keyStats as Prisma.InputJsonValue,
            methodology: draft.methodology,
            dataPeriodStart: draft.dataPeriodStart,
            dataPeriodEnd: draft.dataPeriodEnd,
            dataClass: 'OFFERMARKT',
            sampleSize: draft.sampleSize,
            sampleDescription: draft.sampleDescription,
            authorName: 'Offermarket Insights Engine',
            status: 'DRAFT',
            autoGenerated: true,
            generatedFrom: draft.generatedFrom as Prisma.InputJsonValue,
          },
        });
        created.push({
          slug: draft.slug,
          rule: draft.generatedFrom.rule as RuleId,
          profession: draft.profession,
          regionId: draft.regionId,
        });
      }
    }

    this.logger.log(`Insights generator: ${created.length} draft(s) created, ${skipped} already existed`);
    return { created, skipped, enabled: true };
  }

  // ==========================================================================
  // RULE: monthly salary change per (profession, region)
  // ==========================================================================

  private async salaryChangeDrafts(minChangePct: number) {
    const pairs = await this.prisma.marketSnapshot.findMany({
      distinct: ['profession', 'regionId'],
      select: { profession: true, regionId: true },
      take: 60,
    });

    const drafts: GeneratedDraft[] = [];
    const minCombinedSample = 2 * (await this.config.getThresholds()).SALARY_RANGE;
    for (const pair of pairs) {
      const trends = await this.snapshots.getTrends(pair.profession, 'month', pair.regionId ?? undefined);
      const points = trends.points.filter((p) => p.salaryMedian?.available);
      if (points.length < 2) continue;
      const [prev, cur] = points.slice(-2);
      const changePct = cur.changePct;
      const combinedSample = (cur.salaryMedian?.sampleSize ?? 0) + (prev.salaryMedian?.sampleSize ?? 0);
      if (
        changePct === null ||
        Math.abs(changePct) < minChangePct ||
        combinedSample < minCombinedSample
      ) {
        continue;
      }
      const regionName = pair.regionId
        ? (await this.prisma.region.findUnique({ where: { id: pair.regionId }, select: { name: true } }))?.name ?? null
        : 'the Netherlands';
      const direction = changePct > 0 ? 'increased' : 'decreased';
      const title = `${capitalize(pair.profession)} salary ${direction} ${Math.abs(changePct).toFixed(1)}% in ${regionName}`;
      drafts.push(
        this.buildDraft({
          ruleKey: `salary:${pair.profession}:${pair.regionId ?? 'country'}:${cur.label}`,
          rule: 'SALARY_CHANGE',
          profession: pair.profession,
          regionId: pair.regionId,
          skills: [],
          title,
          summary: `Median annual salary moved from €${prev.salaryMedian!.value!.toLocaleString('en')} to €${cur.salaryMedian!.value!.toLocaleString('en')} (${changePct > 0 ? '+' : ''}${changePct}%) between ${prev.label} and ${cur.label}, based on ${cur.salaryMedian!.sampleSize} verified offers.`,
          category: 'SALARY' as const,
          content: [
            `## What changed`,
            ``,
            `The median annual salary for **${pair.profession}** offers in **${regionName}** was **€${cur.salaryMedian!.value!.toLocaleString('en')}** in ${cur.label}, versus **€${prev.salaryMedian!.value!.toLocaleString('en')}** in ${prev.label} — a change of **${changePct > 0 ? '+' : ''}${changePct}%**.`,
            ``,
            `## How this is computed`,
            ``,
            `From verified offers submitted on Offermarket (data class: Offermarket marketplace data). The median is recomputed nightly from the aggregation engine (method version ${METHOD_VERSION}); each monthly point carries its own sample size. This draft was generated automatically and is awaiting editorial review.`,
            ``,
            `_This article has not been reviewed by an editor yet._`,
          ].join('\n'),
          charts: [
            {
              type: 'bar',
              title: `Median annual salary — ${pair.profession} · ${regionName}`,
              unit: 'EUR/year',
              data: [
                { label: prev.label, value: prev.salaryMedian!.value },
                { label: cur.label, value: cur.salaryMedian!.value },
              ],
            },
          ],
          statistics: [
            {
              key: 'SALARY_TREND',
              label: 'Median salary change',
              value: `${changePct > 0 ? '+' : ''}${changePct}%`,
              dataClass: 'OFFERMARKT',
              sampleSize: cur.salaryMedian!.sampleSize,
            },
          ],
          keyStats: {
            changePct,
            current: cur.salaryMedian!.value,
            previous: prev.salaryMedian!.value,
            currency: 'EUR',
          },
          dataPeriodStart: new Date(`${prev.label}-01`),
          dataPeriodEnd: new Date(`${cur.label}-01`),
          sampleSize: cur.salaryMedian!.sampleSize ?? 0,
          sampleDescription: `Computed from ${cur.salaryMedian!.sampleSize} verified offers submitted on Offermarket.`,
          generatedFrom: {
            rule: 'SALARY_CHANGE',
            ruleKey: `salary:${pair.profession}:${pair.regionId ?? 'country'}:${cur.label}`,
            methodVersion: METHOD_VERSION,
            generatedAt: new Date().toISOString(),
            prevPoint: { label: prev.label, median: prev.salaryMedian!.value, sample: prev.salaryMedian!.sampleSize },
            curPoint: { label: cur.label, median: cur.salaryMedian!.value, sample: cur.salaryMedian!.sampleSize },
          },
        }),
      );
    }
    return drafts;
  }

  // ==========================================================================
  // RULE: per-skill demand growth
  // ==========================================================================

  private async demandGrowthDrafts(minGrowthPct: number) {
    const rows = await this.aggregation.getSkillDemandStats();
    const growing = rows
      .filter((r) => r.growthPct !== null && r.growthPct >= minGrowthPct)
      .sort((a, b) => (b.growthPct ?? 0) - (a.growthPct ?? 0))
      .slice(0, 5);

    return growing.map((row) => {
      const label = row.skill;
      const title = `Demand for ${label} skills ${round1(row.growthPct ?? 0) > 0 ? 'up' : 'flat'} ${Math.abs(row.growthPct ?? 0).toFixed(0)}%`;
      return this.buildDraft({
        ruleKey: `demand:${row.skill}:${new Date().toISOString().slice(0, 7)}`,
        rule: 'DEMAND_GROWTH',
        profession: null,
        regionId: null,
        skills: [row.skill],
        title,
        summary: `Offers involving the ${label} skill grew from ${row.prevOffers} to ${row.offers} (${row.growthPct}%) between the last two windows, based on Offermarket marketplace data.`,
        category: 'DEMAND' as const,
        content: [
          `## What changed`,
          ``,
          `Offers involving the **${label}** skill grew from **${row.prevOffers}** to **${row.offers}** between the previous and current window — a **${row.growthPct}%** increase in demand.`,
          ``,
          `## How this is computed`,
          ``,
          `An offer "involves" a skill when the receiving worker's profile lists it (verified profile skills, data class: Offermarket marketplace data). Growth is only reported when both windows clear the skill minimum; smaller changes are treated as noise. This draft was generated automatically and is awaiting editorial review.`,
          ``,
          `_This article has not been reviewed by an editor yet._`,
        ].join('\n'),
        charts: [
          {
            type: 'bar',
            title: `Offers involving ${label}`,
            unit: 'offers',
            data: [
              { label: 'Previous window', value: row.prevOffers },
              { label: 'Current window', value: row.offers },
            ],
          },
        ],
        statistics: [
          {
            key: 'DEMAND_GROWTH',
            label: 'Demand growth',
            value: `${row.growthPct}%`,
            dataClass: 'OFFERMARKT',
            sampleSize: row.offers,
          },
        ],
        keyStats: { current: row.offers, previous: row.prevOffers, growthPct: row.growthPct },
        dataPeriodStart: new Date(Date.now() - 2 * 90 * 24 * 60 * 60 * 1000),
        dataPeriodEnd: new Date(),
        sampleSize: row.offers,
        sampleDescription: `Computed from ${row.offers} verified offers involving this skill.`,
        generatedFrom: {
          rule: 'DEMAND_GROWTH',
          ruleKey: `demand:${row.skill}:${new Date().toISOString().slice(0, 7)}`,
          methodVersion: METHOD_VERSION,
          generatedAt: new Date().toISOString(),
          current: row.offers,
          previous: row.prevOffers,
        },
      });
    });
  }

  // ==========================================================================
  // RULE: benefit package vs acceptance rate
  // ==========================================================================

  private async benefitImpactDrafts(minSample: number, minGapPct: number) {
    const aggregate = await this.aggregation.getAggregate();
    const benefits = aggregate.competitiveness.benefitCompetitiveness;
    if (
      !benefits.available ||
      !benefits.value?.acceptanceGapPct ||
      (benefits.sampleSize ?? 0) < minSample * 2 ||
      Math.abs(benefits.value.acceptanceGapPct) < minGapPct
    ) {
      return [];
    }
    const gap = benefits.value.acceptanceGapPct;
    const direction = gap > 0 ? 'higher' : 'lower';
    return [
      this.buildDraft({
        ruleKey: `benefit:${new Date().toISOString().slice(0, 7)}`,
        rule: 'BENEFIT_IMPACT',
        profession: null,
        regionId: null,
        skills: [],
        title: `Offers with stronger benefit packages see ${Math.abs(gap).toFixed(0)}% ${direction} acceptance`,
        summary: `Offers with a stronger benefits package (median split across vehicle, tools, training budget, pension and more) are accepted ${Math.abs(gap).toFixed(0)}% ${direction} often than weaker packages, across ${benefits.sampleSize} verified offers.`,
        category: 'EMPLOYER' as const,
        content: [
          `## What we observed`,
          ``,
          `Across **${benefits.sampleSize}** verified offers in the current window, offers whose benefits package scored above the median were accepted **${benefits.value.acceptanceWithBenefitsPct}%** of the time, versus **${benefits.value.acceptanceWithoutBenefitsPct}%** for offers below the median — a gap of **${gap > 0 ? '+' : ''}${gap} percentage points**.`,
          ``,
          `## What counts as a benefit`,
          ``,
          `Each offer is scored on up to 8 benefit indicators present in the structured offer: company vehicle, tools, phone, training budget, pension contribution, travel allowance, remote work — plus a package-strength indicator. Prevalence in this window: company vehicle ${benefits.value.prevalence.vehicle}%, tools ${benefits.value.prevalence.tools}%, training budget ${benefits.value.prevalence.trainingBudget}%.`,
          ``,
          `## How this is computed`,
          ``,
          `Acceptance-rate gap between the two halves of the same window's offers (data class: Offermarket marketplace data). This comparison is correlational, not causal — it is labeled as an observed association, and both cohorts must clear the sample minimum before it is generated. This draft awaits editorial review.`,
          ``,
          `_This article has not been reviewed by an editor yet._`,
        ].join('\n'),
        charts: [
          {
            type: 'bar',
            title: 'Offer acceptance rate by benefit-package strength',
            unit: '%',
            data: [
              { label: 'Above-median package', value: benefits.value.acceptanceWithBenefitsPct },
              { label: 'Below-median package', value: benefits.value.acceptanceWithoutBenefitsPct },
            ],
          },
        ],
        statistics: [
          {
            key: 'BENEFIT_ACCEPTANCE_GAP',
            label: 'Acceptance-rate gap',
            value: `${gap > 0 ? '+' : ''}${gap}pp`,
            dataClass: 'OFFERMARKT',
            sampleSize: benefits.sampleSize,
          },
        ],
        keyStats: {
          acceptanceWithBenefitsPct: benefits.value.acceptanceWithBenefitsPct,
          acceptanceWithoutBenefitsPct: benefits.value.acceptanceWithoutBenefitsPct,
          gapPct: gap,
        },
        dataPeriodStart: new Date(aggregate.period.start),
        dataPeriodEnd: new Date(aggregate.period.end),
        sampleSize: benefits.sampleSize ?? 0,
        sampleDescription: `Computed from ${benefits.sampleSize} verified offers submitted on Offermarket.`,
        generatedFrom: JSON.parse(JSON.stringify({
          rule: 'BENEFIT_IMPACT',
          ruleKey: `benefit:${new Date().toISOString().slice(0, 7)}`,
          methodVersion: METHOD_VERSION,
          generatedAt: new Date().toISOString(),
          benefits,
        })),
      }),
    ];
  }

  // ==========================================================================
  // HELPERS
  // ==========================================================================

  private buildDraft(d: {
    ruleKey: string;
    rule: RuleId;
    profession: string | null;
    regionId: string | null;
    skills: string[];
    title: string;
    summary: string;
    category: 'SALARY' | 'DEMAND' | 'EMPLOYER';
    content: string;
    charts: unknown[];
    statistics: unknown[];
    keyStats: unknown;
    dataPeriodStart: Date;
    dataPeriodEnd: Date;
    sampleSize: number;
    sampleDescription: string;
    generatedFrom: Record<string, unknown>;
  }): GeneratedDraft {
    const period = new Date().toISOString().slice(0, 7);
    return {
      ...d,
      slug: `auto-${slugify(d.ruleKey)}`,
      methodology: `Auto-generated from the Offermarket aggregation engine (method version ${d.generatedFrom.methodVersion}). Rule: ${d.rule}. All numbers are computed from verified submitted offers; nothing is estimated or imputed. See the structured statistics blocks for sample sizes and the data period.`,
    };
  }

  private async findByRuleKey(ruleKey: string) {
    return this.prisma.insightArticle.findFirst({
      where: { generatedFrom: { path: ['ruleKey'], equals: ruleKey } as any },
      select: { id: true },
    });
  }
}

function capitalize(input: string): string {
  return input.length ? input[0].toUpperCase() + input.slice(1) : input;
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 100);
}

interface GeneratedDraft {
  ruleKey: string;
  rule: RuleId;
  profession: string | null;
  regionId: string | null;
  skills: string[];
  title: string;
  summary: string;
  category: 'SALARY' | 'DEMAND' | 'EMPLOYER';
  content: string;
  charts: unknown[];
  statistics: unknown[];
  keyStats: unknown;
  dataPeriodStart: Date;
  dataPeriodEnd: Date;
  sampleSize: number;
  sampleDescription: string;
  generatedFrom: Record<string, unknown>;
  slug: string;
  methodology: string;
}