import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { MarketAggregationService } from './market-aggregation.service';
import { InsightsStatsService } from './insights-stats.service';

/**
 * InsightsDashboardService — the admin Market Intelligence dashboard (P7).
 *
 * Composes the aggregation engine's outputs with platform totals. Every
 * gated metric keeps its GatedValue envelope; nothing here bypasses the
 * sample-size rules that the public product enforces.
 */
@Injectable()
export class InsightsDashboardService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly aggregation: MarketAggregationService,
    private readonly stats: InsightsStatsService,
  ) {}

  async getDashboard() {
    const [totals, nationalAggregate, skills, shortages, pendingDrafts] = await Promise.all([
      this.platformTotals(),
      this.aggregation.getAggregate(),
      this.aggregation.getSkillDemandStats(),
      this.aggregation.getRegionalShortages(),
      this.prisma.insightArticle.count({ where: { autoGenerated: true, status: 'DRAFT', deletedAt: null } }),
    ]);

    // Fastest-growing skills: only rows where growth is actually measurable.
    const fastestGrowingSkills = skills
      .filter((s) => s.growthPct !== null)
      .sort((a, b) => (b.growthPct ?? 0) - (a.growthPct ?? 0))
      .slice(0, 8);
    // Most in-demand skills: current-window volume.
    const mostInDemandSkills = skills.slice(0, 8);

    return {
      totals,
      salary: nationalAggregate.salary,
      demand: nationalAggregate.demand,
      period: nationalAggregate.period,
      mostInDemandSkills,
      fastestGrowingSkills,
      regionalShortages: shortages.slice(0, 10),
      pendingDrafts,
      generatedAt: nationalAggregate.provenance.computedAt,
      methodVersion: nationalAggregate.provenance.methodVersion,
    };
  }

  private async platformTotals() {
    const windowStart = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000);
    const marketStatuses = [
      'SUBMITTED', 'VIEWED', 'SHORTLISTED', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'EXPIRED',
    ] as any[];

    const [activeWorkers, activeEmployers, offersWindow, acceptedOffersWindow] = await Promise.all([
      this.prisma.worker.count({
        where: { deletedAt: null, availability: { not: 'NOT_AVAILABLE' } },
      }),
      this.prisma.employer.count({
        where: { deletedAt: null, verificationStatus: { in: ['BASIC_VERIFIED', 'PREMIUM_VERIFIED'] as any[] } },
      }),
      this.prisma.offer.count({
        where: { status: { in: marketStatuses }, submittedAt: { gte: windowStart } },
      }),
      this.prisma.offer.count({
        where: { status: 'ACCEPTED' as any, submittedAt: { gte: windowStart } },
      }),
    ]);
    return { activeWorkers, activeEmployers, offersWindow, acceptedOffersWindow };
  }
}